name: flutter_restaurant
description: A new Flutter restaurant application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.0.0+9

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  app_links: ^6.0.2
  audioplayers: ^6.0.0
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  circular_countdown_timer: ^0.2.3
  collection: any
  connectivity_plus: ^6.0.3
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  dotted_border: ^2.1.0
  expandable_bottom_sheet: ^1.1.1+1
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  firebase_crashlytics: ^3.5.5
  firebase_messaging: ^14.9.2
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^6.0.4
  flutter_google_places: ^0.3.0
  flutter_inappwebview: ^6.0.0
  flutter_local_notifications: ^17.1.2
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.9
  flutter_typeahead: ^5.2.0
  flutter_widget_from_html_core: ^0.8.5+3
  fwfh_selectable_text: ^0.8.3+1
  geocoding: ^3.0.0
  geolocator: ^11.1.0
  get_it: ^7.7.0
  go_router: ^14.1.1
  google_maps_flutter: ^2.6.1
  google_maps_flutter_web: ^0.5.7
  google_maps_webservice: ^0.0.19
  google_sign_in: ^6.2.1
  http: 0.13.6
  image: ^4.1.7
  image_picker: ^1.1.1
  intl: any
  just_the_tooltip: ^0.0.12
  marquee: ^2.2.3
  mobile_scanner: ^5.1.1
  path_provider: ^2.1.3
  photo_view: ^0.15.0
  pin_code_fields: ^8.0.1
  pinput: ^5.0.0
  provider: ^6.1.2
  scroll_to_index: ^3.0.1
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  shimmer_animation: ^2.1.0+1
  sign_in_with_apple: ^6.1.0
  timezone: ^0.9.3
  universal_html: ^2.2.4
  url_launcher: ^6.2.6
  url_strategy: ^0.2.0
  webview_flutter: ^4.7.0

dependency_overrides:
  webview_flutter_android: 3.16.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_launcher_icons: 0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/logo.png"
  flutter_test:
    sdk: flutter
  fwfh_text_style: ^2.23.8

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/
    - assets/svg/
    - assets/language/
    - assets/json/
    - assets/payment/
    - assets/
    - web/assets/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NunitoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NunitoSans-Bold.ttf
          weight: 700

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
